/* auto-generated by NAPI-RS */
/* eslint-disable */

export interface DetectOptions {
  /** When `true`, the low-accuracy (faster) model is used. */
  lowAccuracy?: boolean
  /** Languages with a confidence score below this threshold are excluded. */
  minConfidence?: number
}

export interface LanguageResult {
  /** ISO 639-1 two-letter code (e.g. `"en"`). */
  iso6391: string
  /** ISO 639-3 three-letter code (e.g. `"eng"`). */
  iso6393: string
  /** Confidence score in the range `[0.0, 1.0]`. */
  confidence: number
}

export interface LinguaDetectionResult {
  /** Detector name — always `"lingua"`. */
  detector: string
  /** Version of the `lingua` crate used at compile time. */
  detectorModelVersion: string
  /** Detected languages, sorted by descending confidence. */
  languages: Array<LanguageResult>
}

export declare function detectLanguage(
  input: Buffer,
  options?: DetectOptions | undefined | null,
): Promise<LinguaDetectionResult>

export declare function detectLanguageMany(
  inputs: Array<Buffer>,
  options?: DetectOptions | undefined | null,
): Promise<LinguaDetectionResult[]>
